<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Imposter" Version="0.1.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
    <PackageReference Include="MassTransit" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eshop.Orders\Eshop.Orders.csproj" />
    <ProjectReference Include="..\Eshop.Inventory\Eshop.Inventory.csproj" />
    <ProjectReference Include="..\Eshop.Events\Eshop.Events.csproj" />
    <ProjectReference Include="..\Eshop.Payment\Eshop.Payment.csproj" />
    <ProjectReference Include="..\Eshop.Catalog\Eshop.Catalog.csproj" />
  </ItemGroup>

</Project>
