<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Imposter" Version="0.1.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.15.3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageReference Include="SharpCompress" Version="0.49.0" />
    <PackageReference Include="Snappier" Version="1.3.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.9.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.6" />
    <PackageReference Include="MassTransit" Version="8.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eshop.Orders\Eshop.Orders.csproj" />
    <ProjectReference Include="..\Eshop.Inventory\Eshop.Inventory.csproj" />
    <ProjectReference Include="..\Eshop.Events\Eshop.Events.csproj" />
    <ProjectReference Include="..\Eshop.Payment\Eshop.Payment.csproj" />
    <ProjectReference Include="..\Eshop.Catalog\Eshop.Catalog.csproj" />
  </ItemGroup>

</Project>
