name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Src/Services/Eshop.slnx

      - name: Check for vulnerable packages
        run: dotnet list Src/Services/Eshop.slnx package --vulnerable

      - name: Build
        run: dotnet build Src/Services/Eshop.slnx --no-restore --configuration Release

      - name: Start MongoDB
        run:|
	   docker run -d --name mongodb -p 27017:27017 mongo:8

          until docker exec mongodb mongosh --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Test
        run: dotnet test Src/Services/Eshop.slnx --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=results.xml" --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/TestResults/*.trx"