name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore Src/Services/Eshop.slnx

      - name: Build
        run: dotnet build Src/Services/Eshop.slnx --no-restore --configuration Release

      - name: Test
        run: dotnet test Src/Services/Eshop.slnx --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=results.xml" --collect:"XPlat Code Coverage"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: "**/*.trx"